### ISSUE TITLE
Extreme lag with seablock mods

### ISSUE THREAD

**Issue by clarfonthey** [dbeckwith/factorio-research-queue#1]
Hey, this mod is excellent UI wise and I love it compared to what it replaces, but I've been playing with seablock mods and recently had to stop using it because it lags a lot (~half a second pause) every time I open the tech tree or the modded queue UI.

Also, I've tried doing some messing around in editor extensions and when I click "research all technologies" it basically freezes the game to the point where I can't while the mod is active. Not quite sure what could be causing this, but figured I'd point it out, since this is a lovely mod.

**Comment by dbeckwith** [comment]
Yeah I've had other reports of it being unusably slow with big mods, so I am aware of it. It's not a straightforward problem to solve though, I need to do some serious profiling and optimization work, and potentially change a lot of the way the UI works. Glad you like the mod, I'll do my best to make improvements as I have time.
