### ISSUE TITLE
Remove __flib GUI subtable

### ISSUE THREAD

**Issue by raiguard** [dbeckwith/factorio-research-queue#2]
Just a heads up, since you've switched to `gui-beta` now, the `global.__flib.gui` subtable is no longer needed and can be removed. :)

**Comment by dbeckwith** [comment]
What is it and how do I remove it? Is it something `flib` created?

Loving the new `gui` library by the way, it's much cleaner to set up event handlers with, and the tag system in Factorio 1.1 is great.

**Comment by raiguard** [comment]
The `__flib` table is generated by flib during a module's `init()` function to hold module-specific stuff. The translation module, for example, holds the pending and future translation requests in its table. The old GUI module held element filters in its subtable, but with the advent of tags, that's no longer needed.

In a migration, just do `global.__flib.gui = nil`.

I agree the new library is so much nicer and simpler to use. Tags are great! ~~I may or may not have added them to the engine myself ;)~~
