### ISSUE TITLE
Dereferencing nil player_data

### ISSUE THREAD

**Issue by sjlevin** [dbeckwith/factorio-research-queue#3]
In several places in actions.lua, there are instances like the following code:
https://github.com/dbeckwith/factorio-research-queue/blob/8a5c33931a584e57c07da5ddc6d59390035bcf4c/scripts/gui/actions.lua#L796-L797

In some mod scenarios, like [Editor Extensions/Testing](https://mods.factorio.com/mod/EditorExtensions) or [Brave New World](https://mods.factorio.com/mod/brave-new-world), there are no player characters and thus `player_data` is `nil` which is later dereferenced. It is not safe to assume that a player will always exist.

**Comment by dbeckwith** [comment]
This mod won't work at all if there are no players, so I'm not sure it's worth handling that case.

**Comment by sjlevin** [comment]
It would be nice if the game didn't crash with this mod installed in scenarios without players. It gets annoying having to disable this mod when I want to do some quick experimentation in a sandbox.

**Comment by dbeckwith** [comment]
Okay I see what you mean. I had a similar experience with the Py Quick Start mod, which used to crash if you started a sandbox game.

The issue with EditorExtensions/testing was actually that the scenario was researching technologies before the player was initialized. Fixed in v0.4.20.
